server.port=8080
spring.application.name=chat-backend
ai.use-mock=false
proxy.enabled=false
proxy.host=127.0.0.1
proxy.port=7890

# 通义千问配置
tongyi.api.key=sk-e75a3809f1fb484392ad899228e5947b
tongyi.api.endpoint=https://dashscope.aliyuncs.com/v1/services/aigc/text-generation/generation
tongyi.api.model=qwen-max